version: '2'
services:
  jenkins:
    image: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/home:/var/jenkins_home
  gitblit:
    image: jacekkow/gitblit
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9418:9418"
    environment:
      JAVA_OPTS: "-Xmx512m"
    volumes:
      - ./gitblit/data:/opt/gitblit-data
    links:
      - jenkins
